|                                      |
|--------------------------------------|
| itle: "Unidad 3"                     |
| uthor: "Carlos Manuel Gómez Miranda" |
| ate: "2023-10-5"                     |
| utput: html_document                 |

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#UNIDAD 3

DECISIONES BAJO RIESGO

##Objetivo: Aplicar criterios de decisión bajo riesgo a problemas que disponen de información para poder elegir con mayor confianza.

##3.1 Criterios para la toma de decisiones sin experimentación

Corresponde a criterios que consideran que el tomador de decisiones casi siempre tendrá alguna informa- ción sobre la posibilidad relativa de los estados de la naturaleza y puede traducirla en una distribución de probabilidad, considerando que el estado de la naturaleza es una variable aleatoria. En este caso la distri- bución se llama distribución deprobabilidad a priori oprevia. Las distribuciones a priori con frecuencia son subjetivas. '

3.1.1 *Criterio de Laplace*

Es un criterio intermedio entre los no probabilísticos y los probabilísticos debido a que propone que, si se ignora por completo el estado de la naturaleza que podría ocurrir, se suponga que todos son igualmente factibles, con lo cual se asigna acada evento la misma probabilidad, se calcula el resultado esperado de cada alternativa y se elige la de mayor pago esperado.

##Ejemplo 3

Aplicar el criterio de Laplace al ejemplo1 para encontrar la decisión recomendada.

##Solución

Dado que existen 3 estados de la naturaleza posiblés, según el criterio de Laplace la probabilidad que se asigna a cada uno es igual a 1/3 y el resultado esperado de cada alternativa es:

Resultado esperado de a~1~ = 1/3(2,000) + 1/3(1,750) + 1/3(1,500) = 1,750

Resultado esperado de a~2~ = 1/3(0) + 1/3 (3,000) + 1/3(6,000) = 3,000

Así, bajo este criterio, la decisión será

max{1,750;3,000}= \$3,000

correspondiente a a~2~, pedir 200 playeras, puesto que su valor esperado es el mayor.

3.1.2 *Criterio de la máxima posibilidad*

En este criterio se identifica el estadode la naturaleza que t1enela probabllldad de ocurrencia más grande y, para este estado, se elige 1aacc1ón con el máximo pagoasociado.

##Ejemplo 4

Para el ejemplo 1, aplique el criterio de la máxima pos¡b1hdad para decidir qué pedido debe solicitarse al proveedor si se estima que la probabilidad de que la demanda sea de 100 playeras es 0.5, de que aumente a 150 prendas es 0.3, y para 200 playeras 0.2 :

+------------------------------------+------------+------------+----------------+
| Accióin (pedido)                   | a~1~       | a~2~       | Probabilidades |
|                                    |            |            |                |
| Estado de la naturaleza (demanda ) | 100        | 200        |                |
+:===================================+:===========+:===========+:===============+
| \$\\theta\$~1~ =100                | 2,000      | 0          | 0.5            |
+------------------------------------+------------+------------+----------------+
| \$\\theta\$~1~ =150                | 1,750      | 3,000      | 0.3            |
+------------------------------------+------------+------------+----------------+
| \$\\theta\$~1~ =200                | 1500       | 6,000      | 0.2            |
+------------------------------------+------------+------------+----------------+

El estado de la naturaleza con mayor probabilidad es \$\\theta\$~1~ ,y para este estado el mejor resultado se obtiene con la acción a~1~ ; por lo tanto la decisión bajo el criterio de la máxima pos¡b1hdad será pedir 100 playeras al proveedor.

3.1.3 *Regla de decisión de Bayes (maximización del valor esperado VEM)*

Usando las mejores estimaciones disponibles de las probabilidades a priori para los estados de la naturaleza, se calcula el valor esperado del pago de cada acción posible y de ellos se elige el mayor Para aplicar este criterio es necesario:

 a) Determinar una probabilidad para cada estado de la naturaleza, de manera que la suma de ellas sea igual a 1.

 b) Calcular el valor esperado (VEM) de cada acción, lo que se obtiene de la suma de los produc- tos de cada resultado por su probabilidad.

 c) Elegir una acción cuyo valor esperado sea el mayor.

Este método puede ajustarse para el cálculo de utilidades esperadas cuando la maximización de los pagos esperados no es un criterio adecuado de elección.

##Ejemplo 5.

Para los datos del ejemplo 4, aplique el criterio del máximo valor esperado (VEM) para dec1d1rqué pedido debe solicitarse al proveedor.

##Solución

 a) P(\$\\theta\$~1~)+P(\$\\theta\$~2~) +P(\$\\theta\$~3~)=1

 b) Calcular el valor esperado de cada acción a; como la suma de los productos del resultado del par (0;, a;) por la probabilidad estimada de 6; :

VEM (a~1~) = 2000 (0.5) + 1750 (0.3) + 1500 (0.2) = 1,825

VEM (a~2~) = 0 (0.5) + 3000 (0.3) + 6000 (0.2) =2,100

 c) El máximo de (1,825; 2,100) = \$2,100. Por lo tanto, la mejor decisión para lograr la meta de maximizar la ganancia esperada (VEM) es a~2~ : hacer un pedido de 200 playeras.

Debe tenerse presente que el VEM es un indicador que resume una estadística completa de resultados, por lo que el decisor puede encontrarse tomando decisiones inconsistentes con sus preferencias psicológicas y sus actitudes frente al riesgo. En la siguiente unidad se presentará la forma de resolver esta problemática.

3.1.4 *Minimización de la pérdida de oportunidad esperada* **(POE)**

La **pérdida de oportunidad esperada** (POE) se calcula utilizando las probabilidades de los estados de la naturaleza como ponderadores de la pérdida de oportunidad obtenida bajo el criterio de Savage. La suma de estos resultados da la *pérdida de oportunidad promedio* para cada acción, y se elige la acción con la menor pérdida de oportunidad esperada (menor arrepentimiento).

##Ejemplo 6

Para el ejemplo 4, determinar la acción que debe elegirse de acuerdo con el criterio de la mínima pérdida de oportunidad esperada (POE).

##Solución

Para la acción a~1~,pedir 100 playeras:

+-------------------------+-------------+--------------+----------------------------------+
| Acción (pedido)         | Pérdida de  | Probabilidad | Pérdida de oportunidad ponderada |
|                         |             |              |                                  |
| Estado de la naturaleza | oportunidad |              |                                  |
|                         |             |              |                                  |
| (demanda)               |             |              |                                  |
+:========================+:============+:=============+:=================================+
| \$\\theta\$~1~ = 100    | 0           | 0.5          | 0                                |
+-------------------------+-------------+--------------+----------------------------------+
| \$\\theta\$~2~ = 150    | 1,250       | 0.3          | 375                              |
+-------------------------+-------------+--------------+----------------------------------+
| \$\\theta\$~3~ = 200    | 4,500       | 0.2          | 900                              |
+-------------------------+-------------+--------------+----------------------------------+
| Pérdida de oportunidad  |             |              | 1,275                            |
|                         |             |              |                                  |
| esperada                |             |              |                                  |
+-------------------------+-------------+--------------+----------------------------------+

Para la acción a~2~, pedir 200 playeras:

+-----------------------------------+-------------+--------------+----------------------------------+
| Acción (pedido)                   | Pérdida de  | Probabilidad | Pérdida de oportunidad ponderada |
|                                   |             |              |                                  |
| Estado de la naturaleza (demanda) | oportunidad |              |                                  |
+:==================================+:============+:=============+:=================================+
| \$\\theta\$~1~ = 100              | 2,000       | 0.5          | 1,000                            |
+-----------------------------------+-------------+--------------+----------------------------------+
| \$\\theta\$~2~ = 150              | 0           | 0.3          | 0                                |
+-----------------------------------+-------------+--------------+----------------------------------+
| \$\\theta\$~3~ = 200              | 0           | 0.2          | 0                                |
+-----------------------------------+-------------+--------------+----------------------------------+
| Pérdida de oportunidad            |             |              | 1,000                            |
|                                   |             |              |                                  |
| esperada                          |             |              |                                  |
+-----------------------------------+-------------+--------------+----------------------------------+

Bajo el criterio de la mínima pérdida de óportunidad esperada, la decisión será:

min{1,275;1,000}= \$1,000

Y corresponde a la accion a~2~ , pedir 200 playeras

Obsérvese que para cada acción la suma del VEM (ejemplo 5) y la POE es la misma cantidad:

Para a~1~ : 1,825 + 1,275 = \$3,000 ; para a~2~ : 2,100 + 1,000 \$3,100

y es, precisamente el valor esperado monetano *en condiciones de certeza.*

##3.2 Valor esperado de la información perfecta (VEIP)

Las probabilidades consideradas para el criterio del VEM se llaman *probabilidades previas* porque fueron establecidas antes de obtener información adicional mediante pruebas, experimentos o muestreo. Por esta razón, la elección de una acción basada en el criterio del VEM también se denomina *análisis previo.* Sin embargo, un dato muy valioso que es común determinar es el *valor de la información perfecta*, y para ello es necesario calcular el *valor* ***esperado*** *de la información perfecta* **(VEIP)**. Se presentan dos de los méto- dos que existen para calcularlo.

3.2.1 *Método 1*

El VEIP se determina restando al valor monetario esperado bajo certeza, el máximo valor esperado bajo incertidumbre, que se ha denotado como VEM:

VEIP = (Valor monetarioesperado) -- (Valor monetarioesperado bajo certeza bajo incertidumbre(VEM))

El valor esperado bajo certeza es el resultado que se obtendría si se pudiéra tomar la decisión después de saber el estado de la naturaleza que se materializó (en cuyo caso se tendría la información perfecta).

##Ejemplo 7

Encontrar el valor esperado de la información perfecta para el ejemplo 4 (página 26).

+-----------------------------------+------------+------------+--------------+
| Acción (pedido)                   | a~1~       | a~2~       | Probabilidad |
|                                   |            |            |              |
| Estado de la naturaleza (demanda) | 100        | 200        |              |
+===================================+============+============+==============+
| \$\\theta\$~1~ = 100              | 2,000      | 0          | 0.5          |
+-----------------------------------+------------+------------+--------------+
| \$\\theta\$~2~ = 150              | 1,750      | 3,000      | 0.3          |
+-----------------------------------+------------+------------+--------------+
| \$\\theta\$~3~ = 200              | 1,500      | 6,000      | 0.2          |
+-----------------------------------+------------+------------+--------------+

Si se conociera el estado de la naturaleza que se presentará, la mejor decisión para cada evento posible sería:

Para \$\\theta\$~1~ = 100, a~1~ ; para \$\\theta\$~2~ = 150, a~2~ y para 0; = 200, también a~2~. Por lo tanto, la *ganancia esperada bajo certeza* es:

GEC = 2,000 (0.5) + 3,000 (0.3) + 6,000 (0.2) = \$3,100

El VEM que se calculó en el ejemplo 5 (página 26) es de \$2,100, entonces el VEIP es igual a

VEIP =3,100 ---2,100 = 1,000

Como \$1,000 es el valor de la información con la que se tomaría "la mejor decisión", sería irracional pagar más \$1,000 por información para determinar la cantidad de playeras que se deben pedir.

3.2.2 *Método 2*

El VEIP es también el valor mínimo de la pérdida de oportunidad esperada (POE) de cada acción ya que, si el decisor supiera qué estado de la naturaleza se presentaría, y actuara racionalmente, trataría de minimizar su pérdida de oportunidad (su arrepentimiento). Por esta razón también se llama *costo de la incertidumbre* a la pérdida de oportunidad esperada (POE).

Revise el ejemplo 6 (página 27) y compruebe que la mínima pérdida de oportunidad esperada se obtuvo para a~2~ y es igual a \$1,000.

El término más general *"valor de la información"* es una medida del mejoramiento de la decisión como resultado de nueva información, y es la diferencia entre el valor esperado de la acción óptima seleccionada después de recibir información adicional, menos el valor esperado de la acción óptima dado el estado de información anterior.

##3.3 Análisis de sensibilidad

Dado que las probabilidades previas tienen un componente de incertidumbre, es útil realizar un análisis de sensibilidad para determinar cómo afecta a la decisión la asignación de probabilidades *a priori*. Este análisis se realiza encontrando los conjuntos de distribuciones de probabilidad en donde una acción determi- nada siempre se prefiere a las otras acciones, porque su valor esperado es el más alto.

##Ejemplo 8

Para el ejemplo 4 del propietario de la tienda de artículos deportivos (página 26), encuentre el conjunto de probabilidades para los cuales la acción a~1~ se prefiere a la acción a~2~

##Solución

El valor esperado de las acciones a~1~ y a~2~ eápresados en términos de probabilidades de los estados de la naturaleza son:

+-----------------------------------+------------+------------+-----------------------------------------+
| Acción (pedido)                   | a~1~       | a~2~       | Probabilidad                            |
|                                   |            |            |                                         |
| Estado de la naturaleza (demanda) | 100        | 200        |                                         |
+===================================+============+============+=========================================+
| \$\\theta\$~1~ = 100              | 2,000      | 0          | p(\$\\theta\$~1~)                       |
+-----------------------------------+------------+------------+-----------------------------------------+
| \$\\theta\$~2~ = 150              | 1,750      | 3,000      | p(\$\\theta\$~2~)                       |
+-----------------------------------+------------+------------+-----------------------------------------+
| \$\\theta\$~3~ = 200              | 1,500      | 6,000      | 1-p(\$\\theta\$~1~) - p(\$\\theta\$~2~) |
+-----------------------------------+------------+------------+-----------------------------------------+

VEM(a~1~)= 2000 p(\$\\theta\$~1~) + 1750 p(\$\\theta\$~2~) + 1500[1---p(\$\\theta\$~1~)--p(\$\\theta\$~2~)]

VEM (a2)= 0 p(\$\\theta\$~1~) + 3000 p(\$\\theta\$~2~) + 6000[1---p(\$\\theta\$~1~)--p(\$\\theta\$~2~)]

Cuando VEM'(a¡) \> VEM (a2), a se prefiere a~2~:

2000 p(\$\\theta\$~1~) + 1750 p(\$\\theta\$~2~) + 1500 [1---p(\$\\theta\$~1~)--p(\$\\theta\$~2~)] \> Op(\$\\theta\$~1~) + 3000 p(\$\\theta\$~2~) + 6000 [1---p(\$\\theta\$~1~)--p(\$\\theta\$~2~)]

Después de simplificar esta expresión se obtiene la désigualdad:

2p(\$\\theta\$~1~)+ p(\$\\theta\$~2~) \> 18/13

A partir de ella se determinan todos los valores de probabilidad p(\$\\theta\$~1~) y p(\$\\theta\$~2~), que cumpl_anlos ax_iomas básicos de probabilidad, para los cuales a¡ debe preferirse sobre a~2~, y al graficarla se visualiza la región de aceptación de la decisión a~1~:

##3.4 Árboles de decisión

Otra forma de estructurar un problema de toma de decisiones para su análisis, consiste en una gráfica que muestra cronológicamente la secuencia de acciones y resultados a medida que se llevan a cabo. En un problema devarias etapas de decisión, se alternan nodos de decisión (de donde parten las ramas que representan las acciones posibles en ese momento del proceso) y los de probabilidad (de donde parten las ramas que representan a los posibles estados de la naturaleza). Al final se indican las consecuencias o resultados de cada rama.

El proceso de análisis representado en un árbol de decisión se llama de inducción regresiva porque, después de construir el árbol, se va evaluando cada ramaa partir del pago o consecuencia final, de la siguiente manera:

1.  El valor esperado de cada nodo de probabilidad se obtiene sumando el valor esperado de cada rama (el producto de la probabilidad por la consecuencia). El resultado se anota en el nodo.

2.  Se comparan los resultados del valor esperado de cada nodo de probabilidad y se elige el que nos acerque más al objetivo del problema. Este valor se coloca en el nodo de decisión que les antecede.

3.  Lasramas del árbol que corresponden a los valores no elegidos se "cierran" debido a que represen- tan acciones cuyos resultados no son racionalmente buenos. Se indica con una doble línea sobre la rama.

##Ejemplo 9 ,

Representar en un diagrama de árbol de decisión el ejemplo 4 y su solución.

##Solución

El diagrama de árbol aparece en la siguiente figura. Obsérvese que el máximo valor esperado se obtiene para la rama a~2~ por lo tanto la decisión debe ser a~2~, pedir 200 playeras, y la decisión a~1~ se descarta. Los pagos están en miles de pesos.

En la gráfica del árbol la ruta por a; "se cierra", y se indica con dos líneas paralelas.

Cuando al tomar una decisión además del valor esperado (VEM) también se considera el *riesgo*, resulta útil representar los resultados posibles de cada acción por medio de una distribución de probabilidad dis- creta, donde dichos resultados son considerados como los valores de una variable aleatoria que tenga probabilidades dadas. Esta gráfica también se llama **perfil de riesgo** de la acción.

##Ejemplo 10

Representar el perfil de riesgo de los resultados de las acciones a~1~ y a~2~ del ejemplo 4 y obtener también las gráficas de las distribuciones de probabilidad acumuladas correspondientes.

##Solución

##3.5 Criterios para la toma de decisiones con experimentación

Se llama también **análisis** ***a posteriori*** porque el VEM (ganancias esperadas) se calcula utilizando las probabilidades *a priori modificadas* a partir de información adicional que se obtiene a través de análisis, experimentación, ensayos, muestreo, etcétera. La intención es reducir la incertidumbre y con ello su costo. Para calcular las *probabilidades revisadas o probabilidades* a posteriori se utiliza el Teorema de Bayes.

Al disponer de más información como resultado de la experimentación, es necesario revisar el valor de la información adicional, es decir, el *valor esperado a posteriori de la información perfecta*. Éste se calcula restando a las ganancias esperadas *a posteriori* **con base en una información perfecta**, las ganancias esperadas *a posteriori*, **calculadas en condiciones de riesgo** (VEM con las probabilidades *a posteriori*). En el análisis *a posteriori* el VEIP será menor que en el caso del análisis *a priori*, cuando se disponía de menos información. '

Por otra parte, también es necesario analizar si vale la pena pagar el costo del muestreo para obtener mayor información, comparándolo con el valor esperado de la información de un plan de muestreo cualquiera.

##Ejemplo 11

Considérese un conjunto de 1,000 urnas identificadas como del tipo \$\\theta\$~1~ y \$\\theta\$~2~ donde cada urna:

\$\\theta\$~1~ contiene 4 bolas rojas y 6 bolas negras, y

\$\\theta\$~2~ contiene 9 bolas rojas y 1 bola negra.

De las 1,000 urnas, 800 son del primer tipo y 200 del segundo.

Una persona selecciona una urna al azar, le quita la etiqueta y la coloca frente a usted pidiéndole que adi- vine qué tipo de urna es. Si usted decide que la urna es del tipo \$\\theta\$~1~ y acierta, gana \$4,000, pero si falla pierde \$2,000; si decide que la urna es del tipo \$\\theta\$~2~ y acierta, gana \$10,000, si se equivoca pierde \$500.

Puede pagar para realizar algunos experimentos a fin de conseguir información adicional o tomar la deci- sión con la información proporcionada. Las condiciones son las siguientes:

$\circ$ e~0~:tomar la decisión con la información disponible.

$\circ$ e~1~; : pagar \$800 y extraer una bola de la urna.

$\circ$ e~2~,:pagar \$1,200 y extraer dos bolas de la urna.

##Solución

Acciones: a~1~ decidir que la urna es del tipo \$\\theta\$~1~

a~2~ decidir que la urna es del tipo \$\\theta\$~2~

a~3~ : no participar en el juego

Estados de la naturaleza:

la ua seleccionada es del tipo \$\\theta\$~1~

la urna seleccionada es del tipo \$\\theta\$~2~

Pagos (resultados):

Si elige a~1~: gana \$4,000 si el verdadero estado de la naturaleza es \$\\theta\$~1~

pierde \$2,000 si el verdadero estado es \$\\theta\$~2~

Si elige a~2~: gana \$10,000 si el verdadero estado es \$\\theta\$~2~

pierde \$500 si el verdadero estado es \$\\theta\$~1~

Si elige a~3~: no gana ni pierde

El siguiente diagrama de árbol representa la secuencia de decisiones que pueden tomarse y los estados de la naturaleza posibles en cada caso. Recuerde que el cálculo de los resultados de cada rama se hace en retroceso.

$\circ$ Análisis de la rama e~0~

Si decide jugar y elige tomar la decisión con la información que posee, se calcula directamente el válor esperado para cada acción posible:

VEM (a~1~) = 4000 (0.8) + (-2000) (0.2) = 2,800

VEM (a~2~) =--- 500 (0.8) + 1000.0 (0.2) = 1,600

VEM (a~3~) =0

max {2,800; 1,600; 0} =2,800

En la rama e~0~ la mejor decisión que se puede tomar es a~1~: decir que la urna es del tipo \$\\theta\$~1~. En tal caso ¿Cuánto estaría dispuesto a pagar por la información perfecta?

VEIP = (Ganancia esperada bajo certeza) ---(VEM máximo)

= 4000(0.8)+ 10000(0.2)---2800= 5200---2800= \$2,400

Este valor también puede obtenerse a partir de la matriz de pérdida de oportunidad:

+-------------------------+--------------+--------------+----------------+
| Acciones                | a~1~         | a~2~         | Probabilidades |
|                         |              |              |                |
| Estado de la naturaleza |              |              |                |
+:========================+:=============+:=============+:===============+
| \$\\theta\$~1~          | 0            | 4,500        | 0.80           |
+-------------------------+--------------+--------------+----------------+
| \$\\theta\$~2~          | 12,000       | 0            | 020            |
+-------------------------+--------------+--------------+----------------+
| POE = VEIP              | 2,400        | 3,600        |                |
+-------------------------+--------------+--------------+----------------+

Por lo tanto, lo más que debería estar dispuesto a pagar por saber el tipo de urna que está frente a usted son \$2,400.

$\circ$ Análisis de la rama e~1~

Después de pagar \$800, la bola que se extrae puede ser roja o negra y con ese resultado se deberá tomar la decisión. Pero ahora la probabilidad de que la urna sea de un tipo o del otro, se modifica en función del color de la bola extraída: si es roja debe calcularse la probabilidad de que la urna sea del tipo \$\\theta\$~1~ dado que la bola que se extrajo fue roja (rama e~1~ , R, a~1~, \$\\theta\$~1~ ) o la probabilidad de que sea del tipo \$\\theta\$~2~ dado que la bola fue roja (rama e~1~, R, a~1~, \$\\theta\$~2~ ):

La probabilidad asignada *a priori* a \$\\theta\$~1~ ,0.8, se cambia por una probabilidad a posteriori y este nuevo valor será menor si la bola fue roja, ya que las urnas tipo \$\\theta\$~1~ tienen menos bolas rojas que las del tipo \$\\theta\$~2~

El mismo cálculo se realiza si la bola extraída es negra, y como las urnas tipo \$\\theta\$~1~ tienen más bolas negras que las del tipo \$\\theta\$~2~ , entonces la probabilidad *a posteriori* en este caso es mayor de 0.8:

Con los valores de las probabilidades revisados a partir de la experimentación, el valor esperado de la información perfecta, si la bola extraída es roja es igual a:

VEIP = 4000 (0.64) + 10000 (0.36) --- 3280

= 6160---3280= \$2,880

En la siguiente tabla aparecen los cálculos del VEM de las dos acciones posibles, la matriz de pérdida de oportunidad y el cálculo de la pérdida de oportunidad esperada que, como se sabe, es otra forma de obtener el VEIP.

Como se observa en la tabla, mientras que en la opción e~0~ ---sinmuestreo---la mejor decisión es a~1~ con un VEM de \$2,800 y el VEIP es de \$2,400, en la opción e~1~ ---quepermite hacer una extracción de la urna---la decisión con el mayor valor esperado es a~2~ con un VEM igual a \$3,280 y el VEIP de \$2,880.

Matriz de decisión                                    Matriz de pérdida de obortunidad

+----------------+----------+---------+----------------------+----------------+--------+--------+
| Estados        | a~1~     | a~2~    | P(\$\\theta\$~1~ /R) | Estados        | a~1~   | a~2~   |
+:===============+:=========+:========+:=====================+:===============+:=======+:=======+
| \$\\theta\$~1~ | 4,000    | --- 500 | 0.64                 | \$\\theta\$~1~ | 0      | 4,500  |
+----------------+----------+---------+----------------------+----------------+--------+--------+
| \$\\theta\$~1~ | ---2,000 | 10,000  | 0.36                 | \$\\theta\$~1~ | 12,000 | 0      |
+----------------+----------+---------+----------------------+----------------+--------+--------+
| VEM            | 1,840    | 3,280   |                      | POE = VEIP     | 4,320  | 2,880  |
+----------------+----------+---------+----------------------+----------------+--------+--------+

Se observa que con Ja información adicional obtenida por la extracción de una bola roja, el valor del VEM se incrementa dado que aumentó la probabilidad de la urna tipo \$\\theta\$~2~ que tiene un "premio" mayor.

También se incrementó el VEIP y la razón es la siguiente: antes de la extracción, la posibilidad de que la urna frente a usted fuera del tipo \$\\theta\$~1~ era mayor (0.8), pero las urnas tipo \$\\theta\$~2~ tienen más bolas rojas, por lo tanto, al sacar una bola roja, aumenta la posibilidad de que la urna sea del tipo \$\\theta\$~2~ y usted estará "menos seguro" de qué tipo de uma tiene frente a usted. Por ello, la información perfectá Itendrá más valor dado que está menos seguro de la respuesta que debe dar.

Por otra parte, la diferencia entre los dos valores del VEM, el de a~1~ en e~0~ y el de a~2~ en e~1~ representa el aumento esperado en el valor del juego debido al experimento de extraer una bola:

3280 ---2800 = 480

Se dice entonces que \$480 es el *valor esperado de la información de la muestra* para el experimento e~1~

El VEIP puede indicar si se debe obtener o no una información muestral imperfecta. Así, si para e; el costo de la experimentación hubiera sido no de \$800 como está planteado, sino mayor de \$2,400 (que es el VEIP para lá decisión que se tomaría sin experimentación), no tendría sentido considerar la rama e~1~

Si la bola que se extrae es negra, el valor monetario esperado y la pérdida de oportunidad esperada co- rrespondientes a cada acción, son los siguientes:

Matriz de decisión Matriz de pérdida de obortunidad

+----------------+----------+---------+---------------------+----------------+---------+---------+
| Estados        | a~1~     | a~2~    | P(\$\\theta\$~1~/N) | Estados        | a~1~    | a~2~    |
+:===============+:=========+:========+:====================+:===============+:========+:========+
| \$\\theta\$~1~ | 4,000    | --- 500 | 0.96                | \$\\theta\$~1~ | 0       | 4,500   |
+----------------+----------+---------+---------------------+----------------+---------+---------+
| \$\\theta\$~1~ | ---2,000 | -10,000 | 0.04                | \$\\theta\$~1~ | 12,000  | 0       |
+----------------+----------+---------+---------------------+----------------+---------+---------+
| VEM            | 3,760    | ---80   |                     | POE = VEIP     | 480     | 4,320   |
+----------------+----------+---------+---------------------+----------------+---------+---------+

En este caso la mejor decisión es a con un VEM de \$3,760 y el VEIP es igual a \$480

Y, como ya se sabe, VEM + POE = constante:

a~1~: 3,760+480 =4,240

a~2~: --80+4,320 =4,240

Continuando con el análisis de inducción regresiva, las probabilidades correspondientes a las ramas (e~1~, R) y (e~1~,N) se calculan de:

El VEM en el nodo de azar antes de la extracción es:

3280 (0.5) + 3760 (0.5) = \$ 3,520

Después de pagar el costo de la experimentación, el valor esperado de la rama e~1~ es

VEM (e~1~) = 3520 ---800 =\$ 2,720

Ladiferencia del VEM entre las ramas e~0~ (sin experimentación) y e~1~ antes de pagar el costo de la experimentación, representa el aumento esperado en el valor del juego debido a la extracción de una bola:

3,520---2,800= \$720

Se dice entonces que el *valor esperado de la información de la muestra* para el experimento e~1~ es de \$720. :

$\circ$ Análisis de la rama e~2~

En este caso la experimentación consiste en extraer dos bolas de la urna pagando \$1,200 y, después de observarlas, decidir qué tipo de urna es.

Las probabilidades de las diferentes rutas del árbol para esta opción de experimentación se calculan como sigue: .

1.  Para la ruta (e~2~, RR, a~1~,\$\\theta\$~1~), las probabilidades a posteriori se calculan de:

2.  Para la ruta (e~2~, RR, a~1~,\$\\theta\$~2~):

3.  Calcule las probabilidades a posteriori de las ramas (e~2~, RR, a~1~,\$\\theta\$~1~) y (e~2~, RR, a~1~,\$\\theta\$~2~), y compruebe que son iguales a las obtenidas para la acción a~1~

4.  Para la ruta (e~2~, RN, a~1~,\$\\theta\$~1~)y también para (e~2~, NR, a~1~,\$\\theta\$~1~) la probabilidad revisada es:

Y, en consecuencia,

5.  Estos mismos valores de probabilidad corresponden a las ramas (e~2~, RN o NR, a~1~,\$\\theta\$~1~) y (e~2~, RN o NR, a~1~,\$\\theta\$~2~).

6.  Rama (e~2~, NN, a~1~,\$\\theta\$~1~):

Por lo tanto,

P(\$\\theta\$~2~/ NN) = 0

Con estos valores se hace el análisis regresivo, calculando el valor esperado de cada nodo de azar y seleccionando la ruta que proporcione el máximo valor futuro en cada nodo de decisión. Las rutas que no co- rresponden a los máximos se "cierran". Como puede observarsc en el árbol, el VEM de cada rama después de pagar la experimentación, si la hay, es:

VEM (es) = \$2,800

VEM (e1) = 3,520 ---800 = \$2,720

VEM (e2) = 4,240 --- 1,200 = \$3,040

VEM (no jugar) = \$ 0

de acuerdo con el criterio del VEM máximo, la decisión debe ser la opción e~2~ pagar \$1,200 para extraer dos bolas de la urna. Si ambas bolas son rojas, decidir a~2~: que la uma es del tipo \$\\theta\$~2~. Si una es roja y la otra negra, decidir a~1~: que la urna es del tipo \$\\theta\$~1~ Si las dos bolas son negras, decidir a~1~: urna tipo \$\\theta\$~1~

3.6 Análisis en la forma extensiva

El proceso del análisis empleado, llamado de inducción regresiva o en retroceso, consta de cuatro pasos:

Paso 1. Estructurar el árbol de decisión en forma cronológica (extensa).

Paso 2. Asignar pagos o utilidades a los extremos de cada rama del árbol.

Paso 3. Asignar probabilidades a todas las ramas que parten de nodos de posibles estados de la naturaleza. "

Paso 4. Calcular los valores esperados por el proceso de inducción en retroceso. Este procedimiento se denomina forma extensiva de análisis.
