---
title: "Grupo de ejercicios 5"
author: "Carlos Manuel Gómez Miranda"
date: "2023-10-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Grupo de ejercicios 5 - -

1\. Una moneda se lanza tres veces seguidas. Recibe \$100 por cada cara (C) que aparezca y \$25 adiciona- 4 les por cada dos caras seguidas que salgan (por ejemplo CCC incluye dos conjuntos de CC). Sin embargo, debe pagar \$110 por cada águila (A) que salga. Tiene la opción de aceptar jugar o no.

 a) Dibuje el árbol de decisión para el juego.

 b) ¿Estaría dispuesto a participar en el juego?

Respuesta: b) VEM(ugar) =-\$2.5; VEM(no jugar) = \$0. No conviene jugar.

2.  Usted tiene la oportunidad de participar en uno de dos negocios que van a establecerse. En el primero

(A~1~) si se tiene éxito obtendría una ganancia de \$100,000; si fracasa perderá \$100,000. En el segundo

(A~2~), si tiene éxito ganará \$10,000 y si fracasa le costará \$10,000.

 a) Dibuje un diagrama de árbol de decisión para ambas situaciones.

 b) Encuentre la mejor decisión de acuerdo con los criterios de decisión bajo completa incertidumbre.

 c) Sipes la probabilidad que asigna al evento "éxito", ¿bajo qué condiciones preferiría usted parti- cipar en A~1~ o en A~2~ y por qué?

 d) Utilizando pesos como variable aleatoria, represente los resultados como una distribución de probabilidad para *p* = 0.25 y para *p* = 0.75 y considere nuevamente su elección. ¿Cómo definiría el riesgo?

Respuestas: b) Maximin y Hurwicz: A,; Savage y Laplace: Ay 0 A;

c)  Si p \<0.5 lo mejor es no participar. Si p = 0.5 elegir A; ó A; dependiendo del riesgo que se este dispuesto a afrontar. .d) Para p=0.25 se es arriesgado; para p = 0.75 se evade el riesgo

```{=html}
<!-- -->
```
3.  La empresa que usted asesora desea invertir \$10,000 dólares en el mercado de valores comprando acciones de una de dos compañías: A o B. Las acciones de la compañía A representan un riesgo pero podrían dar un rendimiento del 50% sobre la inversión el siguiente año. Si las condiciones de la bolsa no son favorables, las acciones pueden perder 20% de su valor. La compañía B proporciona inversiones seguras con 15% de rendimiento en un mercado "a la alza" y sólo 5% en un mercado "a la baja". Todas las publicaciones que ha consultado predicen un 60% de posibilidades para un mercado "a la alza" y 40% para un mercado "a la baja". ¿Dónde aconsejará a la empresa invertir el dinero?

Respuesta: a) En las acciones de la compañía A.

4.  Su empresa ha firmado un contrato con un banco por \$400,000 dólares para proveerle de chips "inteligentes" que integrarán a las nuevas tarjetas de crédito. Su Contador le reportó que los costos de administración, supervisión y de los materiales que requiere, serán de \$200,000 dólares.

En cuanto al costo de la mano de obra, usted y el sindicato acordaron someter a un arbitraje la cuestión u 39 del nivel de habilidad que debe tener el operador de la máquina que la empresa tendrá que adquirir y que sólo es útil para fabricar este pedido. Si usted gana el arbitraje, la mano de obra tendrá un costo de \$8 dólares por hora; si el sindicato gana, el costo será de \$12 dólares por hora. Existen dos tipos de máquina en el mercado: la máquina A cuesta \$140,000 dólares y requerirá 4,000 horas ---hombre para 4 hacer todo el pedido. La máquina B cuesta \$100,000 dólares y necesitará 8,000 horas ---hombre. Desafortunadamente usted debe decidir cual de las dos máquinas comprará varias semanas antes de que pueda conocer el resultado del arbitraje.

Las probabilidades a priori que su abogado.ha establecido para el resultado del arbitraje son del 0.7 para un fallo de \$8 y de 0.3 para el de \$12; pero si el resultado es este último, es posible apelarlo con un costo de \$9,000 dólares en cuyo caso ganar o perder la apelación, tienen la misma probabilidad de ocurrir. Siguiendo el criterio del VEM:

 a) Construya el árbol de decisión del problema.

 b) ¿Qué máquina deberá comprar?

 c) Siel fallo del arbitraje lo obliga a pagar \$12 /hora de trabajo ¿deberá apelar a la resolución?

Respuestas: b) Comprar la máquina B. c) Sí debe apelarse el fallo. Q

5.  Un cliente de una galería de arte está dispuesto a comprar la pintura "Ninfas" en \$50,000. La galería Q) puede adquirir el cuadro hoy por \$40,000 o puede esperar un día y compararlo mañana (si no se ha vendido) por \$30,000. También podría esperar otro día y comprarla, si aún está disponible, por \$26,000. Al final del tercer día la pintura no estará disponible para su venta, Cada día hay una probabi- D5 lidad de 0.6 de que sea vendida. ¿Qué estrategia deberá seguir la galería para maximiza la ganancia esperada?

Respuesta: Comprar el cuadro el primer día.

6.  Un agricultor puede plantar maíz o frijol de soya. Las probabilidades de que los precios de la siguiente cosecha de estos productos aumenten, permanezcan iguales o desciendan son 0.25, 0.30 y 0.45, res- pectivamente. Si los precios aumentan, la cosecha de maíz producirá \$30,000 dólares netos y la soya \$10,000 dólares netos; si permanecen sin cambio apenas quedará "a mano", pero si los precios des- cienden, habrá pérdidas de \$35,000 para la cosecha de maíz y de \$5,000 para la de soya.

 a) Represente el problema en un árbol de decisión

 b) ¿Qué cosecha debe plantar el agricultor?

Respuesta: VEM (maíz) = ---\$8,250; VEM(soya) = \$250, debe plantar frijol de soya.

7.  Lacadena de comida rápida FME está por lanzar a nivel nacional un nuevo tipo de comida. El depar- tamento de investigación está convencido que será un gran éxito y lo quiere introducir de inmediato sin anuncios previos, mientras que el departamento de mercadotecnia quiere realizar una campaña in- tensiva de publicidad. Esta campaña costará \$100,000 dólares y, si tiene éxito, producirá \$850,000 de ganancia. Si la campaña no tiene éxito (y hay un 30% de posibilidad de ello), el ingreso se estima en sólo \$100,000. Si no se usa la publicidad, el ingreso se estima en \$400,000 con probabilidad de 0.8 si los clientes son receptivos y \$200,000 con probabilidad 0.2 si no lo son.

 a) Dibuje el árbol de decisión.  b) ¿Cuál curso de acción debe seguir FME para lanzar el producto?

Respuesta:Hacer la campañadepublicidad,

8.  Dada la siguiente matriz de pago dada en miles de pesos, represente el perfil de riesgo de cada acción utilizando "miles de pesos" como variable aleatoria:

+-------------------------+---------+---------+---------+---------+--------------+
| Acción                  | a~1~    | a~2~    | a~3~    | a~4~    | Probabilidad |
|                         |         |         |         |         |              |
| Estado de la naturaleza |         |         |         |         |              |
+:========================+:========+:========+:========+:========+:=============+
| \$\\theta\$~1~          | -100    | 60      | 20      | --20    | 0.08         |
+-------------------------+---------+---------+---------+---------+--------------+
| \$\\theta\$~2~          | 160     | 80      | 60      | --100   | 0.10         |
+-------------------------+---------+---------+---------+---------+--------------+
| \$\\theta\$~3~          | 40      | 140     | --60    | --140   | 0.50         |
+-------------------------+---------+---------+---------+---------+--------------+
| \$\\theta\$~4~          | 200     | 40      | 20      | 40      | 0.12         |
+-------------------------+---------+---------+---------+---------+--------------+
| \$\\theta\$~5~          | 0       | 100     | 80      | 400     | 0.20         |
+-------------------------+---------+---------+---------+---------+--------------+

9.  Usted tiene la oportunidad de apostar en el siguiente juego en un casino: se tira un dado dos veces, lo que puede producir uno de cuatro resultados: (1) las dos veces cae el mismo número par, (2) las dos veces cae el mismo número impar, (3) los resultados son par - impar o 1mpar par y (4) todos los demás resultados.

Se le permite apostar a exactamente dos resultados con igual cantidad de dinero. Por ejemplo, puede a apostar los mismos pesos a la pareja par (resultado 1) y a la pareja impar (resultado 2). El pago por cada peso que apueste es de \$2 para el primer resultado, \$1.95 para el segundo y tercer resultados y \$1.50 para el cuarto resultado.

 a) Dibuje el árbol de decisión para eljuego.

 b) ¿Cuáles dos resultados elegiría?

 c) ¿Considera que alguna vez podrá ganar en estejuego?

Respuestas: b) El VEM de las 6 alternativas posibles es: (1,2) =---1.67; (1, 3) =-0.86; (1, 4) =-1.34;

(2, 3) =-0.86; (2, 4) =---1.34; (3, 4) = ---0.53; elegiría (3, 4) y (1, 3) pero no conviene jugar. c) No

10. Una empresa manufacturera produce lotes de artículos con 0.8%, 1%, 1.2% y 1.4% de defectuosos, con una probabilidad de 0.4, 0.3, 0.25 y 0.05, respectivamente. Tres clientes, A, B y C, firman con- tratos para recibir lotes con un máximo de 0.8%, 1.2% y 1.4% de defectuosos, respectivamente. La empresa será penalizada con \$1,000 dólares por punto porcentual si el porcentaje de defectuosos es mayor que el especificado en el contrato.

Por otra parte,suministrar lotes con mayor calidad de la requerida le cuesta a la empresa \$500 dólares por punto porcentual. Si los lotes no se inspeccionan antes del embarque:

 a) Dibuje el árbol de decisión del problema.

 b) ¿Cuál de los tres clientes debe tener la prioridad más alta para recibir su orden apegada al contrato?

Respuesta:b) El clienteC

11. La empresa CAR, S.A. renta automóviles al precio de \$100 por día y cada contrato es exactamente de un día. A su vez, CAR, S.A. alquila los autos a la agencia mayorista "EN-Auto, S.A de C.V." a un costo de \$70 por día, precio que incluyen el mantenimiento de las unidades. El gerente de CAR, S.A. debe solicitar a la agencia mayorista el número de vehículos que necesitará alquilar cada día y entre- gar la solicitud, cuando menos, con una semana de anticipación.

Del registro de operaciones diarias de CAR, S.A. se encuentra el número de solicitudes de renta que ha tenido en los últimos 100 días:

| Demanda | Número de días | Frecuencia relativa |
|:--------|:---------------|:--------------------|
| 11      | 10             | .10                 |
| 12      | 15             | .15                 |
| 13      | 20             | .20                 |
| 14      | 25             | .25                 |
| 15      | 18             | .18                 |
| 16      | 12             | .12                 |

Si se supone que el periodo de 100 días es una muestra representativa del comportamiento aleatorio pa- sado de la demanda, que no habrá cambios futuros en el comportamiento observado de ésta, y que el número de solicitudes para renta es completamente aleatorio, encuentre el número de automóviles que CAR, S.A. deberá solicitar a "EN-Anuto, S.A. de C.V." para maximizar su beneficio neto esperado.

Respuesta: Máximo VEM (13) = \$355; debesolicitar 13unidades.

12\. La corporación AR está considerando 3 opciones para manejar su proceéamiento de datos: continuar con su personal; contratar una asesoría externa para que haga la administración, o una combinación de las dos anteriores. El costo anual de cada opción depende de la demanda futura como sigue:

+--------------------------+----------+---------+-------------+----------------+
| Opciones                 | Personal | Asesor  | Combinación | Probabilidades |
|                          |          |         |             |                |
| Demanda ($\theta$~1~)    | propio   | externo | de los dos  |                |
+:=========================+:=========+:========+:============+:===============+
| Alta                     | 650      | 900     | 800         | 0.2            |
+--------------------------+----------+---------+-------------+----------------+
| Media                    | 650      | 600     | 650         | 0.5            |
+--------------------------+----------+---------+-------------+----------------+
| Baja                     | 600      | 300     | 500         | 0.3            |
+--------------------------+----------+---------+-------------+----------------+

\ a)  ¿Qué alternativa de decisión minimiza el costo esperado de la operación de procesamiento de datos y cuál es el costo anual asociado con esa recomendación?

\ b) Construya un perfil de riesgo para la decisión óptima.

\ c) ¿Cuál es la probabilidad de que el costo exceda de \$700,000.

\ d) Haga el análisis de sensibilidad considerando las acciones a~1~ con a~2~ y a~2~ con a~3~.

Respuesta: a) Contratar un asesor externo; costo esperado: \$ 570,000. c)0.2.
